### ISSUE TITLE
admin rights?

### ISSUE THREAD

**Issue by agramfort** [scikit-learn-contrib/stability-selection#20]
@thuijskens you did not give me admin rights to transfer the repo.

i don't see the settings button.

**Comment by thuijskens** [comment]
Hi @agramfort ! I am unable to locate the settings screen where I can give you admin access:

<img width="1024" alt="screen shot 2018-09-05 at 18 16 08" src="https://user-images.githubusercontent.com/10687691/45121691-3af1a500-b138-11e8-948a-60ecb4c5a7a0.png">

but I have sent you a transfer request of the repository. Perhaps you can use that?

**Comment by agramfort** [comment]
you need to add me to Admins not Collaborators

**Comment by agramfort** [comment]
repo is there https://github.com/scikit-learn-contrib/stability-selection
